package villager.voice;

import java.io.IOException;
import java.nio.charset.Charset;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Loads readable hand-authored phoneme spellings and validates their Sherpa
 * token expansion against the model vocabulary.
 *
 * The source TSV is intentionally readable: word, readable phonemes, and the
 * resulting model-token spelling. The generated lexicon contains only the
 * token spelling Sherpa's non-Piper lexicon frontend expects.
 */
public final class PronunciationLexicon {
    private final Map<String, String> tokenByReadable = new HashMap<String, String>();
    private final Set<String> modelTokens = new HashSet<String>();

    private PronunciationLexicon() {
    }

    /** Compile a readable TSV into a Sherpa word-to-token lexicon file. */
    public static Path compile(Path readableSource, Path tokens, Path output) throws IOException {
        if (readableSource == null || !Files.isRegularFile(readableSource)) {
            throw new IOException("Missing readable pronunciation source: " + readableSource);
        }
        PronunciationLexicon compiler = readableAliases();
        compiler.loadTokens(tokens);
        List<String> outputLines = new ArrayList<String>();
        outputLines.add("# Generated from pronunciation-overrides.tsv; do not edit this file.");
        for (String line : Files.readAllLines(readableSource, Charset.forName("UTF-8"))) {
            String trimmed = line.trim();
            if (trimmed.isEmpty() || trimmed.startsWith("#")) {
                continue;
            }
            String[] fields = line.split("\\t", -1);
            if (fields.length < 2 || fields[0].trim().isEmpty()) {
                throw new IOException("Invalid pronunciation entry: " + line);
            }
            String word = fields[0].trim().toLowerCase(java.util.Locale.ROOT);
            String readable = fields[1].trim();
            if (readable.isEmpty()) {
                throw new IOException("Empty pronunciation for word: " + word);
            }
            String expanded = compiler.expand(readable, word);
            outputLines.add(word + " " + expanded);
        }
        Path parent = output.toAbsolutePath().getParent();
        if (parent != null) {
            Files.createDirectories(parent);
        }
        Files.write(output, (join(outputLines) + "\n").getBytes(Charset.forName("UTF-8")));
        return output;
    }

    private void loadTokens(Path tokens) throws IOException {
        if (tokens == null || !Files.isRegularFile(tokens)) {
            throw new IOException("Missing token vocabulary: " + tokens);
        }
        for (String line : Files.readAllLines(tokens, Charset.forName("UTF-8"))) {
            if (line.isEmpty()) {
                continue;
            }
            String symbol;
            if (line.charAt(0) == ' ') {
                symbol = " ";
            } else {
                String[] fields = line.trim().split("\\s+", 2);
                if (fields.length != 2) {
                    continue;
                }
                symbol = fields[0];
            }
            modelTokens.add(symbol);
        }
        if (modelTokens.isEmpty()) {
            throw new IOException("Token vocabulary is empty: " + tokens);
        }
    }

    private String expand(String readable, String word) throws IOException {
        StringBuilder result = new StringBuilder();
        String[] phonemes = readable.split("-", -1);
        for (String phoneme : phonemes) {
            if (phoneme.isEmpty()) {
                throw new IOException("Pronunciation for '" + word + "' contains an empty phoneme");
            }
            String tokenSequence = tokenByReadable.get(phoneme);
            if (tokenSequence == null) {
                tokenSequence = phoneme;
            }
            for (String token : tokenSequence.split("\\s+")) {
                if (!modelTokens.contains(token)) {
                    throw new IOException("Pronunciation for '" + word + "' uses unknown model token '"
                            + token + "' (readable phoneme '" + phoneme + "')");
                }
                if (result.length() > 0) {
                    result.append(' ');
                }
                result.append(token);
            }
        }
        return result.toString();
    }

    private static String join(List<String> lines) {
        StringBuilder result = new StringBuilder();
        for (String line : lines) {
            result.append(line).append('\n');
        }
        return result.toString().trim();
    }

    /** Add a readable alias for a model token. */
    public PronunciationLexicon alias(String readable, String modelToken) {
        tokenByReadable.put(readable, modelToken);
        return this;
    }

    /** Build the aliases used by the project's hand-authored spelling. */
    public static PronunciationLexicon readableAliases() {
        return new PronunciationLexicon()
                .alias("ah", "ɑ")
                .alias("ae", "æ")
                .alias("ih", "ɪ")
                .alias("eh", "ɛ")
                .alias("uh", "ə")
                .alias("uh2", "ʌ")
                .alias("aw", "ɔ")
                .alias("uu", "ʊ")
                .alias("ee", "i")
                .alias("oo", "u")
                .alias("ng", "ŋ")
                .alias("sh", "ʃ")
                .alias("zh", "ʒ")
                .alias("th", "θ")
                .alias("dh", "ð")
                .alias("er", "ɜ")
                .alias("r-color", "˞")
                .alias("ow", "a ʊ")
                .alias("stress", "ˈ");
    }
}
